version: '3'

services:
  consulServer01:
    image: consul:1.10
    container_name: consulServer01
    hostname: consul01
    command: ['tail', '-f', '/dev/null']
    volumes:
      - ./servers/server01:/etc/consul.d
    ports:
      - "8500:8500"
  consulServer02:
    image: consul:1.10
    container_name: consulServer02
    hostname: consulServer02
    command: ['tail', '-f', '/dev/null']
    volumes:
      - ./servers/server02:/etc/consul.d
  consulServer03:
    image: consul:1.10
    container_name: consulServer03
    hostname: consulServer03
    command: ['tail', '-f', '/dev/null']
    volumes:
      - ./servers/server03:/etc/consul.d
  consulClient1:
    image: consul:1.10
    container_name: consulClient1
    hostname: consulClient1
    command: ['tail', '-f', '/dev/null']
    volumes:
      - ./clients/consul01:/etc/consul.d
  consulClient2:
    image: consul:1.10
    container_name: consulClient2
    hostname: consulClient2
    command: ['tail', '-f', '/dev/null']
    volumes:
      - ./clients/consul02:/etc/consul.d